Fix string handling of redirect_branch_to option
The new redirect_branch_to option broke regular builds:

  File "./run-build", line 101, in __init__
    self.redirect_branch_to = redirect_branch_to
  File "./run-build", line 88, in __setattr__
    self.config.set(None, attr, value)
  File "/usr/lib/python3.4/configparser.py", line 1166, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.4/configparser.py", line 1155, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

ConfigParser doesn't like the default value of None for
redirect_branch_to, so switch it to an empty string.

https://phabricator.endlessm.com/T17256